### PR TITLE
Choose lower apiVersion for VMA

### LINKED ISSUE #883: replay of vkcube with 1.3 instance provokes VMA crash on 1.2 driver
```
[gfxrecon] INFO - Replay adjusted the vkEnumeratePhysicalDevices array count: capture count = 2, replay count = 1
[gfxrecon] INFO - Replay adjusted the vkEnumeratePhysicalDevices array count: capture count = 2, replay count = 1
[gfxrecon] INFO - Replay adjusted the vkGetPhysicalDeviceQueueFamilyProperties array count: capture count = 4, replay count = 3
[gfxrecon] WARNING - The replay device differs from the original capture device; replay may fail due to device incompatibilities:
[gfxrecon] WARNING -   Capture device info:    [vendorID = 0x10de, deviceId = 0x249d, deviceName = NVIDIA GeForce RTX 3070 Laptop GPU]
[gfxrecon] WARNING -   Replay device info:    [vendorID = 0x10de, deviceId = 0x1f07, deviceName = GeForce RTX 2070]
ERROR: ----stderr---------------------------------------------------
Assertion failed: m_VulkanFunctions.vkGetDeviceBufferMemoryRequirements != nullptr, file D:\j\workspace\manual-gfxreconstruct\gfxreconstruct\external\VulkanMemoryAllocator\include\vk_mem_alloc.h, line 14652
```
I suspect we initialize VMA with the recorded capture apiVersion and not the replay created instance API version.

### PR DESCRIPTION
**Pull request by locke-lunarg**
Compare VkPhysicalDevice's ApiVersion and VkInstance's ApiVersion. Lower apiVersion could prevent unsupported issues on VMA.

vkspec:
`If we modify the above example so that the application sets apiVersion to 1.1, then the application must not use Vulkan 1.2 functionality on the physical device that supports Vulkan 1.2.`
It means if vkPhysicalDevice's ApiVersion is higher then vkInstance's apiVersion, the higher version's device's functions shouldn't be used, so we should choose lower apiVersion.

closed: https://github.com/LunarG/gfxreconstruct/issues/883

### CODE REVIEW

File: framework/decode/vulkan_replay_consumer_base.cpp [hunk 1]
```diff
@@ -1821,15 +1821,18 @@ void VulkanReplayConsumerBase::InitializeResourceAllocator(const PhysicalDeviceI
...
-                                            physical_device_info->parent,
-                                            physical_device_info->handle,
-                                            device,
-                                            enabled_device_extensions,
-                                            physical_device_info->capture_device_type,
-                                            physical_device_info->capture_memory_properties,
-                                            *replay_device_info->memory_properties,
-                                            functions);
+    VkResult result = allocator->Initialize(
+        (physical_device_info->parent_api_version < physical_device_info->replay_device_info->properties->apiVersion)
```
Comment (bradgrantham-lunarg) [inline framework/decode/vulkan_replay_consumer_base.cpp:1825]: Could this be `std::min`?

**Review by bradgrantham-lunarg — APPROVED** [review]

File: framework/decode/vulkan_replay_consumer_base.cpp (hunk 1 above)
Comment (locke-lunarg) [reply framework/decode/vulkan_replay_consumer_base.cpp]: Good idea. Fixed.

**Review by bradgrantham-lunarg — APPROVED** [review]
Looks good pending testing!

**Comment by locke-lunarg** [comment]
test passed
