### PR TITLE
Use GetDeviceQueue2 for the queue that has flags.

### LINKED ISSUE #1471: Virtual swapchain and screenshot features are incompatible with protected-capable device queues
**Describe the replay bug:**

When using either virtual swapchain or screenshot options, the replay tool attempts to call `vkGetDeviceQueue` to retrieve a handle to a `VkQueue` object which was originally created with the `VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT` flag.
 
[Vulkan spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetDeviceQueue.html) says this is invalid:

> vkGetDeviceQueue must only be used to get queues that were created with the flags parameter of VkDeviceQueueCreateInfo set to zero. To get queues that were created with a non-zero flags parameter use vkGetDeviceQueue2.

The driver on Pixel 6 seems to tolerate this, but Pixel 4 XL segfaults. This was discovered capturing the Vulkan output of ANGLE, which will always create queues that are protected-capable if it can.

**Verify before submission:**
* Was trimming enabled? No
* Was replayer renamed if necessary? N/A
* Was --sync used if title is known to need forced synchronization? N/A

**Build Environment:**

v1.0.3

**To Reproduce**
- Capture file here: [gles3jni_angle.zip](https://github.com/LunarG/gfxreconstruct/files/14783590/gles3jni_angle.zip)
- Replay:
```
python3 android/scripts/gfxrecon.py replay /data/data/com.lunarg.gfxreconstruct.replay/capture.gfxr --push gles3jni_angle.zip.gfxr --surface-index 0
```

**Screenshots:**

N/A

**System environment:**
 - Google Pixel 4 XL 
 - Adreno 640
 - Android 11

**Title configuration:**
This is 10 frames of an Android GLES3 demo (https://github.com/android/ndk-samples/tree/main/gles3jni) running through ANGLE

**Additional information (optional):**

Stack trace
```
03-27 17:37:10.253  3120  3120 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-27 17:37:10.254  3120  3120 F DEBUG   : Build fingerprint: 'google/coral/coral:11/RQ2A.210505.003/7255357:userdebug/dev-keys'
03-27 17:37:10.254  3120  3120 F DEBUG   : Revision: 'MP1.0'
03-27 17:37:10.254  3120  3120 F DEBUG   : ABI: 'arm64'
03-27 17:37:10.254  3120  3120 F DEBUG   : Timestamp: 2024-03-27 17:37:10-0700
03-27 17:37:10.254  3120  3120 F DEBUG   : pid: 3040, tid: 3096, name: Thread-2  >>> com.lunarg.gfxreconstruct.replay <<<
03-27 17:37:10.254  3120  3120 F DEBUG   : uid: 10618
03-27 17:37:10.254  3120  3120 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
03-27 17:37:10.254  3120  3120 F DEBUG   : Cause: null pointer dereference
03-27 17:37:10.254  3120  3120 F DEBUG   :     x0  b40000701776a370  x1  0000000000000000  x2  0000000000000000  x3  0000006f9e3371a8
03-27 17:37:10.254  3120  3120 F DEBUG   :     x4  b4000070278343f8  x5  b400007207775048  x6  0000000000000000  x7  b400007027834fb0
03-27 17:37:10.254  3120  3120 F DEBUG   :     x8  0000000000000000  x9  0000000001cdc0de  x10 0000000000000018  x11 0000000000000001
03-27 17:37:10.254  3120  3120 F DEBUG   :     x12 0000000000000001  x13 7ed337f6e8a8f157  x14 b40000712777c8ec  x15 b40000712777c8ef
03-27 17:37:10.254  3120  3120 F DEBUG   :     x16 000000729ad35350  x17 0000007298564618  x18 b40000713777c2db  x19 0000006f9e3371a8
03-27 17:37:10.254  3120  3120 F DEBUG   :     x20 0000000000000000  x21 0000000000000000  x22 b40000701776a370  x23 b400007117772860
03-27 17:37:10.254  3120  3120 F DEBUG   :     x24 0000006f9e338cc0  x25 0000006f9e338cc0  x26 0000006f9e338ff8  x27 00000000000fc000
03-27 17:37:10.254  3120  3120 F DEBUG   :     x28 0000006f9e240000  x29 0000006f9e336d30
03-27 17:37:10.254  3120  3120 F DEBUG   :     lr  0000007297d1ea8c  sp  0000006f9e336d30  pc  0000007297d1ea98  pst 0000000060000000
03-27 17:37:10.264  3120  3120 F DEBUG   : backtrace:
03-27 17:37:10.264  3120  3120 F DEBUG   :       #00 pc 000000000001aa98  /system/lib64/libvulkan.so (vulkan::driver::GetDeviceQueue(VkDevice_T*, unsigned int, unsigned int, VkQueue_T**)+84) (BuildId: bfe0d26c892b38ffca636158d720e91d)
03-27 17:37:10.264  3120  3120 F DEBUG   :       #01 pc 0000000000af9708  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (gfxrecon::decode::VulkanVirtualSwapchain::CreateSwapchainResourceData(gfxrecon::decode::DeviceInfo const*, gfxrecon::decode::SwapchainKHRInfo const*, unsigned int, unsigned int*, VkImage_T**, bool)+856) (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.264  3120  3120 F DEBUG   :       #02 pc 0000000000afb1fc  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (gfxrecon::decode::VulkanVirtualSwapchain::GetSwapchainImagesKHR(VkResult, VkResult (*)(VkDevice_T*, VkSwapchainKHR_T*, unsigned int*, VkImage_T**), gfxrecon::decode::DeviceInfo const*, gfxrecon::decode::SwapchainKHRInfo*, unsigned int, unsigned int*, VkImage_T**)+560) (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #03 pc 00000000009c2984  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (gfxrecon::decode::VulkanReplayConsumerBase::OverrideGetSwapchainImagesKHR(VkResult (*)(VkDevice_T*, VkSwapchainKHR_T*, unsigned int*, VkImage_T**), VkResult, gfxrecon::decode::DeviceInfo const*, gfxrecon::decode::SwapchainKHRInfo*, gfxrecon::decode::PointerDecoder<unsigned int, unsigned int>*, gfxrecon::decode::HandlePointerDecoder<VkImage_T*>*)+1068) (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #04 pc 0000000000c3267c  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (gfxrecon::decode::VulkanReplayConsumer::Process_vkGetSwapchainImagesKHR(gfxrecon::decode::ApiCallInfo const&, VkResult, unsigned long, unsigned long, gfxrecon::decode::PointerDecoder<unsigned int, unsigned int>*, gfxrecon::decode::HandlePointerDecoder<VkImage_T*>*)+568) (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #05 pc 0000000000b3c430  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (gfxrecon::decode::VulkanDecoder::Decode_vkGetSwapchainImagesKHR(gfxrecon::decode::ApiCallInfo const&, unsigned char const*, unsigned long)+468) (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #06 pc 0000000000b979f0  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (gfxrecon::decode::VulkanDecoder::DecodeFunctionCall(gfxrecon::format::ApiCallId, gfxrecon::decode::ApiCallInfo const&, unsigned char const*, unsigned long)+5280) (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #07 pc 000000000090d2b8  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (gfxrecon::decode::FileProcessor::ProcessFunctionCall(gfxrecon::format::BlockHeader const&, gfxrecon::format::ApiCallId)+688) (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #08 pc 000000000090ca10  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (gfxrecon::decode::FileProcessor::ProcessBlocks()+320) (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #09 pc 000000000090c3dc  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (gfxrecon::decode::FileProcessor::ProcessNextFrame()+72) (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #10 pc 0000000000904614  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (gfxrecon::application::Application::PlaySingleFrame()+60) (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #11 pc 00000000009043c0  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (gfxrecon::application::Application::Run()+252) (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #12 pc 00000000008e1318  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (android_main+1636) (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #13 pc 0000000001198720  /data/app/~~TFjxJ62r02H3beBE-zYpCg==/com.lunarg.gfxreconstruct.replay-LM7g36h8joli3awlRKb6fQ==/lib/arm64/libgfxrecon-replay.so (BuildId: c29f5eecd809dd5a0befd118214b915d5eefb63c)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #14 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 49090ae59e6ae37f8beae53c551820ad)
03-27 17:37:10.265  3120  3120 F DEBUG   :       #15 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 49090ae59e6ae37f8beae53c551820ad)
```

### PR DESCRIPTION
**Pull request by locke-lunarg**
close: https://github.com/LunarG/gfxreconstruct/issues/1471

1.  If the queue has flags, it has to use `GetDeviceQueue2` to get it.  

2. Add `GetDeviceQueue()` to replace all  `device_table->GetDeviceQueue2` and `device_table->GetDeviceQueue`. To ensure using the correct way to get queue.

### CODE REVIEW

File: framework/decode/vulkan_replay_consumer_base.h [hunk 1]
```diff
@@ -1246,6 +1246,37 @@ class VulkanReplayConsumerBase : public VulkanConsumer
     std::vector<uint8_t> matched_replay_cache_data_;
 };
 
+static VkQueue GetDeviceQueue(const encode::VulkanDeviceTable* device_table,
```
Comment (locke-lunarg) [inline framework/decode/vulkan_replay_consumer_base.h:1249]: I feel that it should have a better place to put this function. Please let me know if you know it.

Comment (bradgrantham-lunarg) [reply framework/decode/vulkan_replay_consumer_base.h:1249]: framework/graphics/vulkan_resources_util.cpp ? You may also be able to factor some code in that file if you make this function life in there.

Comment (mikes-lunarg) [reply framework/decode/vulkan_replay_consumer_base.h:1249]: +1 (if it is easy). `gfxrecon_graphics` is a separate target so if your helper function has too many dependencies on `gfxrecon_decode` then I can see it getting messy and might be better to leave it where it is now.

**Review by mikes-lunarg — APPROVED** [review]
LGTM! I tested with my repro capture from the issue and the crash was fixed.

File: framework/decode/vulkan_replay_consumer_base.h (hunk 1 above)
Comment (locke-lunarg) [reply framework/decode/vulkan_replay_consumer_base.h]: Thanks. I moved this function to `graphics\vulkan_util.h`.

File: framework/graphics/vulkan_util.cpp [hunk 2]
```diff
@@ -40,5 +40,36 @@ void ReleaseLoader(util::platform::LibraryHandle loader_handle)
     }
 }
 
+VkQueue GetDeviceQueue(const encode::VulkanDeviceTable* device_table,
+                       const decode::DeviceInfo*        device_info,
```
Comment (bradgrantham-lunarg) [inline framework/graphics/vulkan_util.cpp:44]: Could we remove the dependency in `vulkan_util` on `decode` if this parameter was just the handle and the creation flags was passed in?

**Review by bradgrantham-lunarg — APPROVED** [review]
Mike had mentioned the depedency on decode - if you can remove it that would be nice.

File: framework/graphics/vulkan_util.cpp (hunk 2 above)
Comment (locke-lunarg) [reply framework/graphics/vulkan_util.cpp]: Moved this function to `decoder_util.h`.

Comment (bradgrantham-lunarg) [reply framework/graphics/vulkan_util.cpp]: My opinion is that `vulkan_util` is the right place for this if instead of taking `decode::DeviceInfo` it could just take a vkDevice and creation flags so that it didn't need to use `decode` namespace.

Comment (locke-lunarg) [reply framework/graphics/vulkan_util.cpp]: Fixed it.

Comment (locke-lunarg) [reply framework/graphics/vulkan_util.cpp]: Undo it.

**Review by bradgrantham-lunarg — APPROVED** [review]
