### PR TITLE
Resolve issues around DebugUtilsCallback()

### LINKED ISSUE #2112: print EXT_debug_utils messages on replay
Certain layers/tools/apps emit debug messages through these channels. RenderDoc, for example, emits all its error messages through here, including the errors when it fails to load its capture layer. gfxr should print these messages on replay for improved debugging.

### PR DESCRIPTION
**Pull request by nickdriscoll-lunarg**
Resolves #2112 

`DebugUtilsCallback` will silently omit messages that don't set `pCallbackData->pMessageIdName`. This causes an issue with layers that don't set that field, such as RenderDoc

This PR makes the function print `(nullptr)` in place of `pCallbackData->pMessageIdName` when it is null.

Additionally, this PR unconditionally registers the debug callback so that messages from layers are displayed even when the captured app didn't set the debug callback, and sets the callback severity based on a new option `--debug-messenger-level`

### CODE REVIEW

**Comment by nickdriscoll-lunarg** [comment]
Converting this to a draft as it turns out we want replay to unconditionally register a debug callback so that layers can print their debug messages, and that's a nontrivial change.

File: framework/decode/vulkan_replay_consumer_base.h [hunk 1]
```diff
@@ -1715,6 +1715,8 @@ class VulkanReplayConsumerBase : public VulkanConsumer
     util::ThreadPool main_thread_queue_;
     util::ThreadPool background_queue_;
 
+    VkDebugUtilsMessengerEXT debug_messenger;
```
Comment (antonio-lunarg) [inline framework/decode/vulkan_replay_consumer_base.h:1718]: nit: `debug_messenger_`

**Review by antonio-lunarg — APPROVED** [review]

File: framework/decode/vulkan_replay_consumer_base.cpp [hunk 2]
```diff
@@ -116,24 +116,28 @@ static VKAPI_ATTR VkBool32 VKAPI_CALL DebugUtilsCallback(VkDebugUtilsMessageSeve
 {
     GFXRECON_UNREFERENCED_PARAMETER(pUserData);
 
-    if ((pCallbackData != nullptr) && (pCallbackData->pMessageIdName != nullptr) &&
-        (pCallbackData->pMessage != nullptr))
+    // Allow pCallbackData->pMessageIdName to be nullptr by defining a default string for message id name
+    const char* message_id_name = "(nullptr)";
+    if (pCallbackData->pMessageIdName != nullptr)
```
Comment (bradgrantham-lunarg) [inline framework/decode/vulkan_replay_consumer_base.cpp:121]: Please (always) put braces around the content of the blocks in an if-then-else.

**Review by bradgrantham-lunarg — COMMENTED** [review]
Looks good to me.  (pending CI passing)

**Review by bradgrantham-lunarg — APPROVED** [review]
