### PR TITLE
Fix dark colors when capture uses an SRGB swapchain-format

### LINKED ISSUE #2414: add option for RGBA -> BGRA swapchain
Many times a capture will replay with colors swizzled because the swapchain uses the wrong format. Would be nice to have an option to correct this.

### PR DESCRIPTION
**Pull request by fabian-lunarg**
follow-up to https://github.com/LunarG/gfxreconstruct/pull/2429

during replay, when we cannot support a requested swapchain VkFormat, we fall back to a 'safe' format.
later during runtime, when `VkImageView`s onto swapchain images are created,
we again have to apply corrections.
in both cases we also need to account for SRGB formats.

e.g. `VK_FORMAT_R8G8B8A8_UNORM` -> `VK_FORMAT_B8G8R8A8_UNORM`
and `VK_FORMAT_R8G8B8A8_SRGB` -> `VK_FORMAT_B8G8R8A8_SRGB`

also: 
during swapchain creation we check for usage of `VK_KHR_swapchain_mutable_format`
apply corrections, if necessary.

fixes #2414

### CODE REVIEW

File: framework/decode/vulkan_replay_consumer_base.cpp [hunk 1]
```diff
@@ -7445,8 +7450,33 @@ VkResult VulkanReplayConsumerBase::OverrideCreateSwapchainKHR(
...
+                    for (uint32_t i = 0; i < format_list_pnext->viewFormatCount; ++i)
+                    {
+                        if (vkuFormatIsSRGB(format_list_pnext->pViewFormats[0]))
+                        {
+                            mutable_srgb = true;
+                            break;
+                        }
+                    }
+
+                    // overwrite existing VkImageFormatListCreateInfo
```
Comment (MarkY-LunarG) [inline framework/decode/vulkan_replay_consumer_base.cpp:7463]: Nit, this should be a warning (maybe just once) that you are overwritting the swapchain format.

**Review by MarkY-LunarG — APPROVED** [review]

File: framework/decode/vulkan_replay_consumer_base.cpp [hunk 2]
```diff
@@ -7445,8 +7450,33 @@ VkResult VulkanReplayConsumerBase::OverrideCreateSwapchainKHR(
...
+            // handle VK_KHR_swapchain_mutable_format
+            if (modified_create_info.flags & VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR)
+            {
+                bool mutable_srgb = false;
+                if (auto* format_list_pnext =
+                        graphics::vulkan_struct_get_pnext<VkImageFormatListCreateInfo>(&modified_create_info))
+                {
+                    for (uint32_t i = 0; i < format_list_pnext->viewFormatCount; ++i)
+                    {
+                        if (vkuFormatIsSRGB(format_list_pnext->pViewFormats[0]))
```
Comment (bradgrantham-lunarg) [inline framework/decode/vulkan_replay_consumer_base.cpp]: Should this be checking pViewFormats[i]?

File: framework/decode/vulkan_replay_consumer_base.cpp [hunk 3]
```diff
@@ -7445,8 +7450,33 @@ VkResult VulkanReplayConsumerBase::OverrideCreateSwapchainKHR(
 
         if (!surface_format_supported)
         {
+            // handle VK_KHR_swapchain_mutable_format
+            if (modified_create_info.flags & VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR)
+            {
+                bool mutable_srgb = false;
+                if (auto* format_list_pnext =
```
Comment (bradgrantham-lunarg) [inline framework/decode/vulkan_replay_consumer_base.cpp:7456]: Could this be `any_of`?  Something like
```
bool mutable_srgb = std::any_of(format_list_pnext->pViewFormats, format_list_pnext->pViewFormats + format_list_pnext->viewFormatCount, vkuFormatIsSRGB);

```

File: framework/decode/vulkan_replay_consumer_base.cpp (hunk 2 above)
Comment (fabian-lunarg) [reply framework/decode/vulkan_replay_consumer_base.cpp]: yes, thanks for catching!

File: framework/decode/vulkan_replay_consumer_base.cpp (hunk 1 above)
Comment (fabian-lunarg) [reply framework/decode/vulkan_replay_consumer_base.cpp:7463]: already in place. couple lines below, we log "Replay adjusted unsupported surface imageFormat (%d) to VK_FORMAT_B8G8R8A8_UNORM". 

this added block is dealing with `VK_KHR_swapchain_mutable_format`, mostly in order to avoid validation-errors:
```
[gfxrecon] ERROR - DEBUG MESSENGER: Frame #1: VUID-VkSwapchainCreateInfoKHR-flags-03168: vkCreateSwapchainKHR(): pCreateInfo->flags includes VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR but none of the elements of the pViewFormats member of VkImageFormatListCreateInfo match imageFormat (VK_FORMAT_B8G8R8A8_UNORM).
The Vulkan spec states: If flags contains VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR then the pNext chain must include a VkImageFormatListCreateInfo structure with a viewFormatCount greater than zero and pViewFormats must have an element equal to imageFormat
```
so here, we're not really swapping the format, rather adjust the list of compatible/mutable formats that `VkImageView`s created onto the swapchain-images 'could' have.

File: framework/decode/vulkan_replay_consumer_base.cpp (hunk 3 above)
Comment (fabian-lunarg) [reply framework/decode/vulkan_replay_consumer_base.cpp:7456]: yes, much nicer. done

File: framework/decode/vulkan_replay_consumer_base.cpp (hunk 2 above)
Comment (fabian-lunarg) [reply framework/decode/vulkan_replay_consumer_base.cpp]: -> now using `std::any_of`
