### PR TITLE
allocate s_alt_stack at startup with size probed from system

### LINKED ISSUE #545: page_guard_manager.cpp:113:28: error: size of array ‘s_alt_stack’ is not an integral constant-expression   113 | static uint8_t s_alt_stack[SIGSTKSZ];
```
$ mkdir build && cd build/ && cmake ../
-- The C compiler identification is GNU 11.1.1
-- The CXX compiler identification is GNU 11.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Vulkan Header = /home/mikhail/packaging-work/git/gfxreconstruct/external/Vulkan-Headers/include/vulkan/vulkan_core.h
-- Detected Vulkan Version 1.2.176
-- Found LZ4: /usr/lib64/liblz4.so  
-- Found ZSTD: /usr/lib64/libzstd.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-keysyms.so;/usr/lib64/libX11-xcb.so  
-- Found WAYLAND: /usr/lib64/libwayland-client.so  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib64/libX11.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for clock_gettime in c
-- Looking for clock_gettime in c - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mikhail/packaging-work/git/gfxreconstruct/build

$ make
[  1%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/argument_parser.cpp.o
[  2%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/file_output_stream.cpp.o
[  3%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/file_path.cpp.o
[  4%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/hash.cpp.o
[  5%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/image_writer.cpp.o
[  6%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/keyboard.cpp.o
[  7%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/logging.cpp.o
[  8%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/lz4_compressor.cpp.o
[  9%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/zlib_compressor.cpp.o
[ 10%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/zstd_compressor.cpp.o
[ 11%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/memory_output_stream.cpp.o
[ 12%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/monotonic_allocator.cpp.o
[ 13%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/page_guard_manager.cpp.o
In file included from /usr/include/signal.h:328,
                 from /home/mikhail/packaging-work/git/gfxreconstruct/framework/util/platform.h:52,
                 from /home/mikhail/packaging-work/git/gfxreconstruct/framework/util/logging.h:28,
                 from /home/mikhail/packaging-work/git/gfxreconstruct/framework/util/page_guard_manager.cpp:27:
/home/mikhail/packaging-work/git/gfxreconstruct/framework/util/page_guard_manager.cpp:113:28: error: size of array ‘s_alt_stack’ is not an integral constant-expression
  113 | static uint8_t s_alt_stack[SIGSTKSZ];
      |                            ^~~~~~~~
make[2]: *** [framework/util/CMakeFiles/gfxrecon_util.dir/build.make:244: framework/util/CMakeFiles/gfxrecon_util.dir/page_guard_manager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:384: framework/util/CMakeFiles/gfxrecon_util.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### PR DESCRIPTION
**Pull request by bradgrantham-lunarg**
Fixes #545

### CODE REVIEW

File: framework/util/page_guard_manager.h [hunk 1]
```diff
@@ -181,6 +181,8 @@ class PageGuardManager
   private:
     size_t GetSystemPageSize() const;
     size_t GetSystemPagePotShift() const;
+    size_t InitSystemExceptionHandler() const;
```
Comment (locke-lunarg) [inline framework/util/page_guard_manager.h:184]: No definition of  InitSystemExceptionHandler()?

Comment (bradgrantham-lunarg) [reply framework/util/page_guard_manager.h:184]: Must have made that prototype and then not used it, instead making InitializeSystemExceptionContext. I'll delete.

**Review by locke-lunarg — APPROVED** [review]

**Review by patrick-lunarg — APPROVED** [review]
