### PR TITLE
Report frame number in debug callback during replay

### LINKED ISSUE #1859: Add frame number to messages received through debug utils
This would allow a user of CDL to localize a crash to a short sequence of frames, make a trimmed recapture of those frames, and use that recapture to more quickly investigate bugs and make repro case.  @jeremyg-lunarg 

GFXR also may not be setting up debug utils messengers correctly, needs investigation as part of this task.

### PR DESCRIPTION
**Pull request by nickdriscoll-lunarg**
Fixes #1859 

This PR adds logic to propagate the frame number down from the FileProcessor to the consumers, so that the frame number can appear in messages emitted by the debug callback.

### CODE REVIEW

File: framework/decode/vulkan_replay_consumer_base.cpp [hunk 1]
```diff
@@ -119,7 +119,8 @@ static VKAPI_ATTR VkBool32 VKAPI_CALL DebugUtilsCallback(VkDebugUtilsMessageSeve
                                                          const VkDebugUtilsMessengerCallbackDataEXT* pCallbackData,
                                                          void*                                       pUserData)
 {
-    GFXRECON_UNREFERENCED_PARAMETER(pUserData);
+    VulkanReplayConsumerBase* replay_consumer = static_cast<VulkanReplayConsumerBase*>(pUserData);
+    uint64_t frame_number = replay_consumer->GetFrameNumber() + 1; // Add 1 because of one-based indexing of frames
```
Comment (antonio-lunarg) [inline framework/decode/vulkan_replay_consumer_base.cpp]: I would move this `+ 1; // Add 1 because of one-based indexing of frames` to the `GetFrameNumber()` implementation.

File: framework/decode/vulkan_replay_consumer_base.h [hunk 2]
```diff
@@ -307,6 +309,8 @@ class VulkanReplayConsumerBase : public VulkanConsumer
 
     void InitializeReplayDumpResources();
 
+    uint64_t GetFrameNumber();
```
Comment (antonio-lunarg) [inline framework/decode/vulkan_replay_consumer_base.h]: this can be `const`

File: framework/decode/vulkan_replay_consumer_base.cpp (hunk 1 above)
Comment (nickdriscoll-lunarg) [reply framework/decode/vulkan_replay_consumer_base.cpp]: Of course

File: framework/decode/vulkan_replay_consumer_base.h (hunk 2 above)
Comment (nickdriscoll-lunarg) [reply framework/decode/vulkan_replay_consumer_base.h]: Oh ok. TIL what `const` means in the context of method declaration.

File: framework/decode/api_decoder.h [hunk 3]
```diff
@@ -199,6 +199,8 @@ class ApiDecoder
 
     virtual void SetCurrentBlockIndex(uint64_t block_index){};
 
+    virtual void SetCurrentFrameNumber(uint64_t frame_number){};
```
Comment (antonio-lunarg) [inline framework/decode/api_decoder.h:203]: So the getter is returning a 1-based frame number. But the setter is expecting 0-based, right? I would add documentation for that to avoid confusion.

Comment (nickdriscoll-lunarg) [reply framework/decode/api_decoder.h:203]: Good point. Documented it.

**Review by antonio-lunarg — APPROVED** [review]

**Review by bradgrantham-lunarg — APPROVED** [review]
