### PR TITLE
Fix trim with external formats

### LINKED ISSUE #1901: Android games that use AHB will crash on trim
Images that are created with external formats are not handled correctly in the vulkan_state_writter.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #1901 

Replaces #1695

This only fixes the crash, there is a `Todo` left that is waiting on #1812

### CODE REVIEW

**Comment by bradgrantham-lunarg** [comment]
I've removed myself from reviewers for this one instance.  If @mikes-lunarg and @antonio-lunarg approve the PR, please merge it.

File: framework/decode/vulkan_replay_consumer_base.cpp [hunk 1]
```diff
@@ -5113,6 +5121,19 @@ VulkanReplayConsumerBase::OverrideCreateImage(PFN_vkCreateImage
         {
             image_info->queue_family_index = 0;
         }
+
+        auto external_format_android = graphics::vulkan_struct_get_pnext<VkExternalFormatANDROID>(replay_create_info);
+        if (external_format_android && external_format_android->externalFormat != 0)
```
Comment (antonio-lunarg) [inline framework/decode/vulkan_replay_consumer_base.cpp:5126]: Please use `auto *` and explicitly check with `!= nullptr`

File: framework/decode/vulkan_replay_consumer_base.cpp [hunk 2]
```diff
@@ -4745,6 +4745,14 @@ VkResult VulkanReplayConsumerBase::OverrideBindImageMemory(PFN_vkBindImageMemory
             image_info->handle, image_info->allocator_data, memory_info->allocator_data);
     }
 
+    if (image_info->external_format)
```
Comment (antonio-lunarg) [inline framework/decode/vulkan_replay_consumer_base.cpp:4748]: Please, add this comment here as well.
```
// Memory requirements for image with external format can only be queried after the memory is bound
```

File: framework/decode/vulkan_replay_consumer_base.cpp [hunk 3]
```diff
@@ -5113,6 +5121,19 @@ VulkanReplayConsumerBase::OverrideCreateImage(PFN_vkCreateImage
         {
             image_info->queue_family_index = 0;
         }
+
+        auto external_format_android = graphics::vulkan_struct_get_pnext<VkExternalFormatANDROID>(replay_create_info);
+        if (external_format_android && external_format_android->externalFormat != 0)
+        {
+            image_info->external_format = true;
```
Comment (antonio-lunarg) [inline framework/decode/vulkan_replay_consumer_base.cpp:5128]: Please, add this comment here as well.
```
// Memory requirements for image with external format can only be queried after the memory is bound
```

File: framework/encode/vulkan_state_tracker.cpp [hunk 4]
```diff
@@ -556,6 +556,16 @@ void VulkanStateTracker::TrackImageMemoryBinding(
     {
         wrapper->bind_pnext = vulkan_trackers::TrackStruct(bind_info_pnext, wrapper->bind_pnext_memory);
     }
+
+    // AHB image memory requirements can only be queried after the memory is bound
+    if (wrapper->external_format)
+    {
+        const VulkanDeviceTable* device_table = vulkan_wrappers::GetDeviceTable(device);
+        VkMemoryRequirements     image_mem_reqs;
+        assert(wrapper->handle != VK_NULL_HANDLE);
```
Comment (antonio-lunarg) [inline framework/encode/vulkan_state_tracker.cpp:565]: Prefer `GFXRECON_ASSERT`, but I think you can use `image` directly.

File: framework/encode/vulkan_state_tracker_initializers.h [hunk 5]
```diff
@@ -652,6 +652,12 @@ inline void InitializeState<VkDevice, vulkan_wrappers::ImageWrapper, VkImageCrea
     assert(wrapper->handle != VK_NULL_HANDLE);
     device_table->GetImageMemoryRequirements(parent_handle, wrapper->handle, &image_mem_reqs);
     wrapper->size = image_mem_reqs.size;
+
+    auto external_format_android = graphics::vulkan_struct_get_pnext<VkExternalFormatANDROID>(create_info);
+    if (external_format_android && external_format_android->externalFormat != 0)
```
Comment (antonio-lunarg) [inline framework/encode/vulkan_state_tracker_initializers.h:657]: ditto

File: framework/encode/vulkan_state_tracker_initializers.h [hunk 6]
```diff
@@ -652,6 +652,12 @@ inline void InitializeState<VkDevice, vulkan_wrappers::ImageWrapper, VkImageCrea
     assert(wrapper->handle != VK_NULL_HANDLE);
     device_table->GetImageMemoryRequirements(parent_handle, wrapper->handle, &image_mem_reqs);
     wrapper->size = image_mem_reqs.size;
```
Comment (antonio-lunarg) [inline framework/encode/vulkan_state_tracker_initializers.h:654]: What's the result here when the format is external?

File: framework/encode/vulkan_state_writer.cpp [hunk 7]
```diff
@@ -2759,17 +2763,26 @@ void VulkanStateWriter::WriteImageMemoryState(const VulkanStateTable& state_tabl
...
-                                                                                             &snapshot_info.level_sizes,
-                                                                                             true);
+                    if (wrapper->external_format)
+                    {
+                        snapshot_info.resource_size = wrapper->size;
+                        snapshot_info.level_sizes.push_back(wrapper->size);
+                    }
+                    else
+                    {
+                        snapshot_info.resource_size =
```
Comment (antonio-lunarg) [inline framework/encode/vulkan_state_writer.cpp:2773]: Why can't we use `wrapper->size` here?

Comment (ziga-lunarg) [reply framework/encode/vulkan_state_writer.cpp:2773]: Because `snapshot_info.level_sizes` needs to be filled in. AHB cannot have mip levels so it is easier there

File: framework/encode/vulkan_state_tracker_initializers.h (hunk 6 above)
Comment (ziga-lunarg) [reply framework/encode/vulkan_state_tracker_initializers.h]: Good catch, it is not valid to call `vkGetImageMemoryRequirements` before memory is bound when you have external memory.

**Review by antonio-lunarg — APPROVED** [review]
