### PR TITLE
convert: Fix binary out dir when stdout used

### LINKED ISSUE #2202: gfxrecon-convert dumps binaries to 'stdout' directory
Command:
`gfxrecon-convert --output stdout --include-binaries trace.gfxr`
will currently send json data to stdout and create "stdout" directory in the trace directory for the binary data.

The expected behavior is the binaries are created in the directory that matches the trace file name, as by default.

Additionally, for automation purposes it would be useful to have a `--binary-output` parameter allowing to specify a separate binary directory.

### PR DESCRIPTION
**Pull request by MarkY-LunarG**
When stdout is set for the output, and a "--include-binaries" option is used, we were outputting to a folder called "stdout". This should not have been the case because according to our own usage info, it should have reverted to the GFXR capture file name.

Fixes #2202

### CODE REVIEW

**Comment by fabian-lunarg** [comment]
wrt. compilation-issue. we'll need to rebase after https://github.com/LunarG/gfxreconstruct/pull/2309 has been merged.

File: framework/decode/json_writer.cpp [hunk 1]
```diff
@@ -223,11 +223,16 @@ void RepresentBinaryFile(JsonWriter&             writer,
...
         if (writer.WriteBinaryFile(filepath, data_size, data))
         {
-            FieldToJson(jdata, basename, json_options);
+            std::string file_only_name = filename;
+            size_t      last_slash_pos = file_only_name.find_last_of("/\\");
+            if (last_slash_pos >= 0)
+            {
+                file_only_name.replace(0, last_slash_pos + 1, "");
+            }
+            FieldToJson(jdata, file_only_name, json_options);
```
Comment (fabian-lunarg) [inline framework/decode/json_writer.cpp]: we could use [STL](https://en.cppreference.com/w/cpp/filesystem/path/filename.html) like `std::string file_only_name = std::filesystem::path(filepath).filename().string();` ?

Comment (MarkY-LunarG) [reply framework/decode/json_writer.cpp]: I forgot we're up to 17 at least now.  Thanks for reminding me!

**Comment by fabian-lunarg** [comment]
95% sure the CI fail is due to recent .jsonl groundtruth-update. in this case a rebase should fix it
