### PR TITLE
Don't always use VK_KHR_surface_capabilities2 when trimming

### LINKED ISSUE #2247: [replay] Trimmed replay uses VK_KHR_get_surface_capabilities2 without enabling it, crashes with RenderDoc
**Describe the replay bug:**
Trimmed replay unconditionally uses entry points from VK_KHR_get_surface_capabilities2, even if the capture application does not enable it

This shows up as validation errors during replay:
```
[gfxrecon] ERROR - DEBUG MESSENGER: UNASSIGNED-GeneralParameterError-ExtensionNotEnabled: vkGetPhysicalDeviceSurfaceCapabilities2KHR(): function required extension VK_KHR_get_surface_capabilities2 which has not been enabled.

[gfxrecon] ERROR - DEBUG MESSENGER: UNASSIGNED-GeneralParameterError-ExtensionNotEnabled: vkGetPhysicalDeviceSurfaceFormats2KHR(): function required extension VK_KHR_get_surface_capabilities2 which has not been enabled.

[gfxrecon] ERROR - DEBUG MESSENGER: UNASSIGNED-GeneralParameterError-ExtensionNotEnabled: vkGetPhysicalDeviceSurfaceFormats2KHR(): function required extension VK_KHR_get_surface_capabilities2 which has not been enabled.
```
When used in with RenderDoc, this causes a crash in the RenderDoc capture layer dispatch code

**To Reproduce**
1. Take a trimmed capture of vkcube
2. Replay with validation enabled OR take a RenderDoc capture of the replay

### PR DESCRIPTION
**Pull request by mikes-lunarg**
Capture was automatically upgrading trimmed vkGetPhysicalDeviceSurfaceCapabilitiesKHR calls into vkGetPhysicalDeviceSurfaceCapabilities2KHR calls, whether or not the VK_KHR_surface_capabilities2 extension was actually enabled. This causes a replay validation error (and a crash when replayed through RenderDoc) if the original capture did not use VK_KHR_surface_capabilities2. The fix is to track which version of the capability and format queries was captured and then write the same version to the trimmed capture file.

Fixes #2247

### CODE REVIEW

**Comment by mikes-lunarg** [comment]
JSON diff for `wait-for-present_frame_2.gfxr`:
```diff
--- build/install/test/known_good/wait-for-present_frame_2.json 2025-06-25 08:28:38.050881305 -0700
+++ build/install/test/wait-for-present_frame_2.json    2025-06-25 08:28:38.043881351 -0700
@@ -601,40 +559,32 @@
 {
   "index": 22,
   "function": {
-    "name": "vkGetPhysicalDeviceSurfaceCapabilities2KHR",
+    "name": "vkGetPhysicalDeviceSurfaceCapabilitiesKHR",
     "thread": 1,
     "return": "VK_SUCCESS",
     "args": {
       "physicalDevice": 4,
-      "pSurfaceInfo": {
-        "sType": "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SURFACE_INFO_2_KHR",
-        "surface": 3,
-        "pNext": null
-      },
+      "surface": 3,
       "pSurfaceCapabilities": {
-        "sType": "VK_STRUCTURE_TYPE_SURFACE_CAPABILITIES_2_KHR",
-        "surfaceCapabilities": {
-          "minImageCount": 1,
-          "maxImageCount": 0,
-          "currentExtent": {
-            "width": 4294967295,
-            "height": 4294967295
-          },
-          "minImageExtent": {
-            "width": 1,
-            "height": 1
-          },
-          "maxImageExtent": {
-            "width": 65535,
-            "height": 65535
-          },
-          "maxImageArrayLayers": 128,
-          "supportedTransforms": "0x000001ff",
-          "currentTransform": "VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR",
-          "supportedCompositeAlpha": "0x0000000f",
-          "supportedUsageFlags": "0x000000ff"
-        },
-        "pNext": null
+        "minImageCount": 1,
+        "maxImageCount": 0,
+        "currentExtent": {
+          "width": 4294967295,
+          "height": 4294967295
+        },
+        "minImageExtent": {
+          "width": 1,
+          "height": 1
+        },
+        "maxImageExtent": {
+          "width": 65535,
+          "height": 65535
+        },
+        "maxImageArrayLayers": 128,
+        "supportedTransforms": "0x000001ff",
+        "currentTransform": "VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR",
+        "supportedCompositeAlpha": "0x0000000f",
+        "supportedUsageFlags": "0x000000ff"
       }
     }
   }
@@ -642,16 +592,12 @@
 {
   "index": 23,
   "function": {
-    "name": "vkGetPhysicalDeviceSurfaceFormats2KHR",
+    "name": "vkGetPhysicalDeviceSurfaceFormatsKHR",
     "thread": 1,
     "return": "VK_SUCCESS",
     "args": {
       "physicalDevice": 4,
-      "pSurfaceInfo": {
-        "sType": "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SURFACE_INFO_2_KHR",
-        "surface": 3,
-        "pNext": null
-      },
+      "surface": 3,
       "pSurfaceFormatCount": 2,
       "pSurfaceFormats": null
     }
@@ -660,33 +606,21 @@
 {
   "index": 24,
   "function": {
-    "name": "vkGetPhysicalDeviceSurfaceFormats2KHR",
+    "name": "vkGetPhysicalDeviceSurfaceFormatsKHR",
     "thread": 1,
     "return": "VK_SUCCESS",
     "args": {
       "physicalDevice": 4,
-      "pSurfaceInfo": {
-        "sType": "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SURFACE_INFO_2_KHR",
-        "surface": 3,
-        "pNext": null
-      },
+      "surface": 3,
       "pSurfaceFormatCount": 2,
       "pSurfaceFormats": [
         {
-          "sType": "VK_STRUCTURE_TYPE_SURFACE_FORMAT_2_KHR",
-          "surfaceFormat": {
-            "format": "VK_FORMAT_B8G8R8A8_UNORM",
-            "colorSpace": "VK_COLOR_SPACE_SRGB_NONLINEAR_KHR"
-          },
-          "pNext": null
+          "format": "VK_FORMAT_B8G8R8A8_UNORM",
+          "colorSpace": "VK_COLOR_SPACE_SRGB_NONLINEAR_KHR"
         },
         {
-          "sType": "VK_STRUCTURE_TYPE_SURFACE_FORMAT_2_KHR",
-          "surfaceFormat": {
-            "format": "VK_FORMAT_R8G8B8A8_UNORM",
-            "colorSpace": "VK_COLOR_SPACE_SRGB_NONLINEAR_KHR"
-          },
-          "pNext": null
+          "format": "VK_FORMAT_R8G8B8A8_UNORM",
+          "colorSpace": "VK_COLOR_SPACE_SRGB_NONLINEAR_KHR"
         }
       ]
     }
```

File: framework/encode/vulkan_handle_wrappers.h [hunk 1]
```diff
@@ -517,25 +517,37 @@ struct CommandPoolWrapper : public HandleWrapper<VkCommandPool>
...
-    VkPhysicalDeviceSurfaceInfo2KHR surface_info;
-    std::unique_ptr<uint8_t[]>      surface_info_pnext_memory;
+    // For vkGetPhysicalDeviceSurfaceCapabilitiesKHR
+    VkSurfaceKHR             surface{ VK_NULL_HANDLE };
+    VkSurfaceCapabilitiesKHR surface_capabilities;
 
-    VkSurfaceCapabilities2KHR  surface_capabilities;
-    std::unique_ptr<uint8_t[]> surface_capabilities_pnext_memory;
+    // For vkGetPhysicalDeviceSurfaceCapabilities2KHR
+    bool use_surface_capabilities2{ false };
```
Comment (panos-lunarg) [inline framework/encode/vulkan_handle_wrappers.h]: Is it possible that we need to differentiate even between `2` and `2KHR`?

I was doing a similar change for `vkCreateRenderPass` and it made a difference whether the application was calling `2` and I latter called `2KHR` with getting a warning `Unsupported function vkCreateRenderPass2KHR was called, resulting in no-op behavior`.

Comment (mikes-lunarg) [reply framework/encode/vulkan_handle_wrappers.h]: Good point. We can reuse the tracking structs between 2/2KHR but the entry points are not interchangeable.

Comment (mikes-lunarg) [reply framework/encode/vulkan_handle_wrappers.h]: Wait, there is no `vkGetPhysicalDeviceSurfaceCapabilities2` since WSI functions don't get promoted to core.

Comment (panos-lunarg) [reply framework/encode/vulkan_handle_wrappers.h]: doh, you're right

**Comment by mikes-lunarg** [comment]
Rebased and implemented @bradgrantham-lunarg's `std::variant` suggestion from https://github.com/LunarG/gfxreconstruct/pull/2250#discussion_r2169334129

**Review by fabian-lunarg — APPROVED** [review]
