### PR TITLE
Escaped Strings in JSON Header

### LINKED ISSUE #1014: header field emitted by `convert` may need to escape filename
```
$ head -1 gfxr_20230227T142500.jsonl
{"header":{"source-path":"C:\Users\Locke\Documents\Works\gfxreconstruct\build\tools\replay\Debug\gfxr_20230227T142500.gfxr","json-version":"0.8.0","gfxrecon-version":"0.9.19-dev (fake6:a459d62+dx12)","vulkan-version":"1.3.241"}}

$ head -1 gfxr_20230227T142500.jsonl | jq-win64.exe '.'
parse error: Invalid escape at line 1, column 123
```
If I change all those `\` to `\\`, jq parses it fine.

It's easy enough to work around for now: `tail +2 gfxr_20230227T142500.jsonl | jq '.'` or edit and delete the first line.

### PR DESCRIPTION
**Pull request by andrew-lunarg**
Absolute path to gfxr trace file verified as accepted by chocolatey-installed jq under ARM64 Windows 11 Powershell.

Fixes #1014

### CODE REVIEW

File: framework/decode/vulkan_ascii_consumer_base.cpp [hunk 1]
```diff
@@ -85,9 +85,9 @@ void VulkanAsciiConsumerBase::Initialize(FILE*      file,
         fprintf(file_,
                 "{\"header\":{\"source-path\":\"%s\",\"json-version\":"
                 "\"" GFXRECON_CONVERT_JSON_VERSION "\",\"gfxrecon-version\":\"%s\",\"vulkan-version\":\"%s\"}}\n",
-                inputFilepath,
-                gfxrVersion,
-                vulkanVersion);
+                util::JSONEscape(inputFilepath).c_str(),
+                util::JSONEscape(gfxrVersion).c_str(),
+                util::JSONEscape(vulkanVersion).c_str());
```
Comment (andrew-lunarg) [inline framework/decode/vulkan_ascii_consumer_base.cpp:90]: I escaped them all just in case.

**Review by bradgrantham-lunarg — APPROVED** [review]
